import { useMemo, useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { motion } from 'framer-motion';
import { ArrowRight, Bot, CheckCircle2, ChevronLeft, Crown, Loader2, Search, ShieldCheck, Users } from 'lucide-react';
import { useAuth } from '@/context/AuthContext';
import { useGuild } from '@/context/GuildContext';
import { formatNumber, getGuildIconUrl } from '@/lib/utils';

const BOT_INVITE = 'https://discord.com/oauth2/authorize?client_id=1478877109538652371&permissions=8&integration_type=0&scope=bot';

export default function GuildSelect() {
  const navigate = useNavigate(); const { guilds } = useAuth(); const { selectGuild } = useGuild();
  const [search, setSearch] = useState(''); const [selectedId, setSelectedId] = useState<string | null>(null);
  const visibleGuilds = useMemo(() => guilds.filter((guild) => guild.owner || (guild.permissions & 0x8) === 0x8 || (guild.permissions & 0x20) === 0x20).filter((guild) => guild.name.toLowerCase().includes(search.toLowerCase())), [guilds, search]);
  const manage = (guildId: string) => { setSelectedId(guildId); selectGuild(guildId); navigate('/dashboard/home', { replace: true }); };
  return <div className="min-h-screen bg-dark-900 text-white"><div className="pointer-events-none fixed inset-0 civrat-grid opacity-60" /><div className="pointer-events-none fixed -top-40 right-0 h-96 w-96 rounded-full bg-neon-green/10 blur-[100px]" />
    <header className="relative z-10 border-b border-white/10 bg-dark-900/70 backdrop-blur-xl"><div className="mx-auto flex h-18 max-w-7xl items-center justify-between px-4 sm:px-6"><Link to="/" className="flex items-center gap-2 text-sm text-dark-300 hover:text-white"><ChevronLeft className="h-4 w-4" />Accueil</Link><div className="font-black tracking-[.18em]"><b className="text-neon-green">CIV</b><b className="text-neon-yellow">RAT</b></div><div className="hidden text-xs text-dark-300 sm:block">Connexion sécurisée Discord</div></div></header>
    <main className="relative z-10 mx-auto max-w-7xl px-4 py-12 sm:px-6 lg:py-16"><div className="mb-10 flex flex-col gap-6 lg:flex-row lg:items-end lg:justify-between"><div><div className="inline-flex items-center gap-2 rounded-full border border-neon-green/20 bg-neon-green/8 px-3 py-1 text-xs font-bold text-neon-green"><ShieldCheck className="h-3.5 w-3.5" />SERVEURS AUTORISÉS</div><h1 className="mt-4 text-4xl font-black tracking-tight sm:text-5xl">Choisissez votre <span className="text-gradient-gold">communauté</span></h1><p className="mt-3 max-w-2xl text-dark-300">Seuls les serveurs dont vous êtes propriétaire ou administrateur sont affichés.</p></div><div className="relative w-full lg:max-w-sm"><Search className="pointer-events-none absolute left-4 top-1/2 h-4 w-4 -translate-y-1/2 text-neon-green" /><input value={search} onChange={(event) => setSearch(event.target.value)} className="input-field pl-11" placeholder="Rechercher un serveur…" aria-label="Rechercher un serveur" /></div></div>
      <div className="mb-6 flex items-center justify-between text-sm"><span className="text-dark-300"><b className="text-white">{visibleGuilds.length}</b> serveur{visibleGuilds.length !== 1 ? 's' : ''} disponible{visibleGuilds.length !== 1 ? 's' : ''}</span><span className="hidden text-dark-300 sm:block">Étape 2 sur 2</span></div>
      {visibleGuilds.length ? <div className="grid gap-5 sm:grid-cols-2 xl:grid-cols-3">{visibleGuilds.map((guild, index) => { const icon = getGuildIconUrl(guild.id, guild.icon); const installed = guild.bot_present; return <motion.article key={guild.id} initial={{ opacity: 0, y: 16 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: index * .04 }} className="group relative overflow-hidden rounded-2xl border border-white/10 bg-dark-800/80 p-5 shadow-xl shadow-black/10 transition hover:-translate-y-1 hover:border-neon-green/30"><div className="absolute -right-12 -top-12 h-32 w-32 rounded-full bg-neon-green/8 blur-3xl group-hover:bg-neon-green/14" /><div className="relative flex items-start justify-between gap-4"><div className="flex min-w-0 items-center gap-4">{icon ? <img src={icon} alt="" className="h-14 w-14 rounded-2xl object-cover" /> : <div className="grid h-14 w-14 shrink-0 place-items-center rounded-2xl bg-gradient-to-br from-neon-green to-neon-yellow text-xl font-black text-dark-900">{guild.name.charAt(0)}</div>}<div className="min-w-0"><h2 className="truncate text-lg font-bold">{guild.name}</h2><p className="mt-1 flex items-center gap-1.5 text-xs text-dark-300"><Users className="h-3.5 w-3.5" />{guild.member_count ? `${formatNumber(guild.member_count)} membres` : 'Serveur Discord'}</p></div></div>{guild.owner ? <span title="Propriétaire" className="rounded-lg bg-neon-yellow/15 p-2 text-neon-yellow"><Crown className="h-4 w-4" /></span> : <span title="Administrateur" className="rounded-lg bg-neon-green/10 p-2 text-neon-green"><ShieldCheck className="h-4 w-4" /></span>}</div><div className="relative mt-6 flex items-center justify-between border-t border-white/8 pt-4"><span className={installed ? 'inline-flex items-center gap-1.5 text-xs font-bold text-neon-green' : 'inline-flex items-center gap-1.5 text-xs font-bold text-neon-yellow'}>{installed ? <CheckCircle2 className="h-4 w-4" /> : <Bot className="h-4 w-4" />}{installed ? 'CIVRAT est installé' : 'Bot à installer'}</span>{installed ? <button disabled={selectedId === guild.id} onClick={() => manage(guild.id)} className="btn-primary inline-flex items-center gap-2 !px-3 !py-2 text-sm">{selectedId === guild.id ? <Loader2 className="h-4 w-4 animate-spin" /> : <>Tableau de bord <ArrowRight className="h-4 w-4" /></>}</button> : <a href={BOT_INVITE} className="btn-secondary inline-flex items-center gap-2 !px-3 !py-2 text-sm">Ajouter le bot <ArrowRight className="h-4 w-4" /></a>}</div></motion.article>; })}</div> : <div className="rounded-3xl border border-dashed border-white/15 bg-dark-800/50 px-6 py-20 text-center"><ShieldCheck className="mx-auto h-10 w-10 text-dark-300" /><h2 className="mt-4 text-xl font-bold">Aucun serveur trouvé</h2><p className="mt-2 text-sm text-dark-300">Essayez une autre recherche ou vérifiez vos permissions Discord.</p></div>}</main>
  </div>;
}
