import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { motion } from 'framer-motion';
import { AlertTriangle, ArrowRight, BarChart3, Bot, Check, Gift, Globe2, Lock, MessageCircle, Shield, Ticket, Users, Zap } from 'lucide-react';

const BOT_INVITE = 'https://discord.com/oauth2/authorize?client_id=1478877109538652371&permissions=8&integration_type=0&scope=bot';
type Locale = 'fr' | 'en';
const copy = {
  fr: { features: 'Fonctionnalités', documentation: 'Documentation', support: 'Support Discord', login: 'Connexion Discord', add: 'Ajouter le bot', badge: 'LA GESTION DISCORD, RÉINVENTÉE', titleA: 'Votre communauté.', titleB: 'Votre contrôle.', description: 'Une expérience de gestion Discord rapide, élégante et pensée pour les communautés qui veulent aller plus loin.', explore: 'Découvrir le dashboard', trusted: 'Tout ce dont votre serveur a besoin', stats: [['Serveurs', '50K+'], ['Membres protégés', '2M+'], ['Modules', '20+']], product: 'Produit', community: 'Communauté', legal: 'Légal', coming: 'À venir', rights: 'Tous droits réservés.' },
  en: { features: 'Features', documentation: 'Documentation', support: 'Discord Support', login: 'Discord Login', add: 'Add the bot', badge: 'DISCORD MANAGEMENT, REIMAGINED', titleA: 'Your community.', titleB: 'Your control.', description: 'A fast, elegant Discord management experience built for communities that want to go further.', explore: 'Explore dashboard', trusted: 'Everything your server needs', stats: [['Servers', '50K+'], ['Members protected', '2M+'], ['Modules', '20+']], product: 'Product', community: 'Community', legal: 'Legal', coming: 'Coming soon', rights: 'All rights reserved.' },
} as const;
const features = [{ icon: Shield, title: 'Auto Moderation', text: 'Filters, anti-spam and intelligent protection.' }, { icon: Users, title: 'Welcome & Roles', text: 'A polished member journey from the first message.' }, { icon: Ticket, title: 'Tickets', text: 'A focused workspace for your support team.' }, { icon: Zap, title: 'XP & Levels', text: 'Reward activity and keep your community engaged.' }, { icon: Gift, title: 'Giveaways', text: 'Create memorable moments in a few clicks.' }, { icon: Lock, title: 'Security', text: 'Keep your community safe from raids and abuse.' }, { icon: BarChart3, title: 'Analytics', text: 'Turn activity into useful, clear insights.' }, { icon: AlertTriangle, title: 'Anti-Nuke', text: 'Additional protection for your Discord server.' }];

export default function Landing() {
  const [locale, setLocale] = useState<Locale>(() => localStorage.getItem('civrat-locale') === 'fr' || navigator.language.startsWith('fr') ? 'fr' : 'en');
  useEffect(() => { localStorage.setItem('civrat-locale', locale); document.documentElement.lang = locale; }, [locale]);
  const t = copy[locale];
  return <div className="min-h-screen overflow-hidden bg-dark-900 text-white selection:bg-neon-green selection:text-dark-900">
    <div className="pointer-events-none fixed inset-0 civrat-grid" /><div className="pointer-events-none fixed -top-56 left-1/2 h-[38rem] w-[38rem] -translate-x-1/2 rounded-full bg-neon-green/10 blur-[120px]" />
    <header className="relative z-20 border-b border-white/8 bg-dark-900/70 backdrop-blur-xl"><nav className="mx-auto flex h-18 max-w-7xl items-center justify-between px-4 sm:px-6 lg:px-8">
      <Link to="/" className="flex items-center gap-2 font-black tracking-[.18em]"><span className="grid h-9 w-9 place-items-center rounded-xl bg-gradient-to-br from-neon-green to-neon-yellow text-dark-900"><Bot className="h-5 w-5" /></span><span><b className="text-neon-green">CIV</b><b className="text-neon-yellow">RAT</b></span></Link>
      <div className="hidden items-center gap-6 text-sm text-dark-300 lg:flex"><a href="#features" className="hover:text-white">{t.features}</a><a href="#documentation" className="hover:text-white">{t.documentation}</a><a href="https://discord.gg/BA3aDFqtXr" target="_blank" rel="noreferrer" className="hover:text-white">{t.support}</a></div>
      <div className="flex items-center gap-2"><button onClick={() => setLocale(locale === 'fr' ? 'en' : 'fr')} aria-label="Change language" className="rounded-lg border border-white/10 px-2.5 py-2 text-xs font-bold text-dark-300 hover:text-white">{locale.toUpperCase()}</button><Link to="/login" className="btn-secondary hidden sm:block !px-4 !py-2">{t.login}</Link><a href={BOT_INVITE} className="btn-primary !px-4 !py-2">{t.add}</a></div>
    </nav></header>
    <main className="relative z-10"><section className="mx-auto max-w-7xl px-4 pb-20 pt-24 text-center sm:px-6 lg:px-8 lg:pb-32 lg:pt-32"><motion.div initial={{ opacity: 0, y: 15 }} animate={{ opacity: 1, y: 0 }} className="mx-auto inline-flex items-center gap-2 rounded-full border border-neon-green/25 bg-neon-green/8 px-3 py-1.5 text-xs font-bold tracking-wider text-neon-green"><span className="h-1.5 w-1.5 animate-pulse rounded-full bg-neon-green" />{t.badge}</motion.div><motion.h1 initial={{ opacity: 0, y: 25 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: .1 }} className="mx-auto mt-7 max-w-5xl text-5xl font-black leading-[.95] tracking-tight sm:text-7xl lg:text-8xl">{t.titleA}<br /><span className="text-gradient-gold">{t.titleB}</span></motion.h1><motion.p initial={{ opacity: 0 }} animate={{ opacity: 1 }} transition={{ delay: .2 }} className="mx-auto mt-7 max-w-2xl text-base leading-7 text-dark-300 sm:text-lg">{t.description}</motion.p><motion.div initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: .3 }} className="mt-9 flex flex-col justify-center gap-3 sm:flex-row"><Link to="/login" className="btn-primary inline-flex items-center justify-center gap-2 !px-6 !py-3.5">{t.explore}<ArrowRight className="h-4 w-4" /></Link><a href="https://discord.gg/BA3aDFqtXr" target="_blank" rel="noreferrer" className="btn-secondary inline-flex items-center justify-center gap-2 !py-3.5"><MessageCircle className="h-4 w-4" />{t.support}</a></motion.div></section>
      <section className="mx-auto grid max-w-5xl grid-cols-1 gap-px overflow-hidden rounded-2xl border border-white/10 bg-white/10 sm:grid-cols-3">{t.stats.map(([label, value]) => <div key={label} className="bg-dark-800/80 px-7 py-6 text-center"><strong className="block text-3xl font-black text-neon-green">{value}</strong><span className="mt-1 text-sm text-dark-300">{label}</span></div>)}</section>
      <section id="features" className="mx-auto max-w-7xl px-4 py-28 sm:px-6 lg:px-8"><div className="mb-12 max-w-xl"><p className="text-sm font-bold uppercase tracking-widest text-neon-green">CIVRAT</p><h2 className="mt-3 text-4xl font-black">{t.trusted}</h2></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{features.map(({ icon: Icon, title, text }) => <motion.article whileHover={{ y: -5 }} key={title} className="module-card group !cursor-default"><div className="mb-5 grid h-11 w-11 place-items-center rounded-xl bg-neon-green/10 text-neon-green ring-1 ring-neon-green/20 group-hover:bg-neon-green group-hover:text-dark-900"><Icon className="h-5 w-5" /></div><h3 className="font-bold">{title}</h3><p className="mt-2 text-sm leading-6 text-dark-300">{text}</p></motion.article>)}</div></section>
      <section id="documentation" className="mx-auto max-w-5xl px-4 pb-28 sm:px-6"><div className="relative overflow-hidden rounded-3xl border border-neon-green/20 bg-gradient-to-br from-neon-green/10 via-dark-800 to-neon-yellow/8 p-8 text-center sm:p-14"><Globe2 className="mx-auto h-8 w-8 text-neon-yellow" /><h2 className="mt-4 text-3xl font-black">CIVRAT, built for every community.</h2><p className="mx-auto mt-3 max-w-xl text-dark-300">Documentation and guides are being prepared. Join our Discord to get help from the community.</p><a href="https://discord.gg/BA3aDFqtXr" target="_blank" rel="noreferrer" className="btn-primary mt-7 inline-flex gap-2">{t.support}<ArrowRight className="h-4 w-4" /></a></div></section>
    </main>
    <footer className="relative z-10 border-t border-white/10 bg-dark-800/50"><div className="mx-auto grid max-w-7xl gap-10 px-4 py-14 sm:grid-cols-2 lg:grid-cols-5 sm:px-6"><div><div className="font-black tracking-[.18em]"><b className="text-neon-green">CIV</b><b className="text-neon-yellow">RAT</b></div><p className="mt-3 text-sm text-dark-300">Discord, elevated.</p></div><FooterGroup title={t.product} links={[t.features, 'Dashboard', t.add, t.documentation]} /><FooterGroup title={t.community} links={[t.support]} /><FooterGroup title={t.legal} links={[`${locale === 'fr' ? 'Politique de confidentialité' : 'Privacy policy'} (${t.coming})`, `${locale === 'fr' ? 'Conditions d’utilisation' : 'Terms of service'} (${t.coming})`]} /><FooterGroup title="Social" links={['Twitter (X)', 'TikTok', 'Instagram']} /></div><div className="border-t border-white/8 py-5 text-center text-xs text-dark-300">© {new Date().getFullYear()} CIVRAT. {t.rights}</div></footer>
  </div>;
}
function FooterGroup({ title, links }: { title: string; links: readonly string[] }) { return <div><h3 className="text-sm font-bold">{title}</h3><ul className="mt-4 space-y-2.5">{links.map((link) => <li key={link}><a href="#" onClick={(event) => event.preventDefault()} className="text-sm text-dark-300 hover:text-neon-green">{link}</a></li>)}</ul></div>; }
