const { ActionRowBuilder, ButtonBuilder, ButtonStyle, EmbedBuilder, PermissionsBitField } = require("discord.js");
const { sendLog } = require("./logService");
const logger = require("../utils/logger");

function canSend(channel, guild) { return Boolean(channel?.isTextBased?.() && guild.members.me && channel.permissionsFor(guild.members.me)?.has(PermissionsBitField.Flags.SendMessages)); }
function panel(config) { return { embeds: [new EmbedBuilder().setColor("#39ff14").setTitle("🛡 Vérification CIVRAT").setDescription("Cliquez sur le bouton ci-dessous pour vérifier votre compte et recevoir votre rôle.").setTimestamp()], components: [new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId("captcha_verify").setLabel("Vérifier mon compte").setStyle(ButtonStyle.Success).setEmoji("✅"))] }; }
async function sendPanel(guild, config) { if (!config.captcha_enabled) throw new Error("Captcha désactivé"); const channel = guild.channels.cache.get(config.captcha_channel_id); if (!canSend(channel, guild)) throw new Error("Salon de vérification inaccessible"); await channel.send(panel(config)); return channel; }
async function sendReminder(member, config) { if (!config.captcha_enabled || !config.captcha_channel_id || member.user.bot) return; const role = member.guild.roles.cache.get(config.captcha_role_id); if (role && member.roles.cache.has(role.id)) return; try { await member.user.send(`🛡 Bienvenue sur **${member.guild.name}**. Vérifiez votre compte dans <#${config.captcha_channel_id}>.`); } catch (error) { logger.warn(`Captcha reminder unavailable for ${member.user.tag}: ${error.message}`); } }
async function verify(interaction) { try { if (!interaction.guild) return interaction.reply({ content: "❌ Cette vérification doit être utilisée dans le serveur.", ephemeral: true }); const config = await require("./guildConfig").getGuildConfig(interaction.guild.id); if (!config.captcha_enabled) return interaction.reply({ content: "❌ La vérification est désactivée.", ephemeral: true }); const role = interaction.guild.roles.cache.get(config.captcha_role_id); if (!role || !interaction.member.manageable) { await sendLog(interaction.guild, config, "log_moderation_channel_id", { title: "🛡 Échec vérification", color: "danger", target: `${interaction.user} (${interaction.user.id})`, fields: [{ name: "Raison", value: !role ? "Rôle configuré introuvable" : "Membre non gérable" }] }); return interaction.reply({ content: config.captcha_failure_message || "❌ Vérification impossible.", ephemeral: true }); } if (interaction.member.roles.cache.has(role.id)) return interaction.reply({ content: "ℹ️ Vous êtes déjà vérifié.", ephemeral: true }); await interaction.member.roles.add(role, "Vérification CIVRAT"); await sendLog(interaction.guild, config, "log_moderation_channel_id", { title: "✅ Membre vérifié", color: "success", target: `${interaction.user} (${interaction.user.id})`, fields: [{ name: "Rôle attribué", value: `${role}` }] }); return interaction.reply({ content: config.captcha_success_message || "✅ Vous avez été vérifié !", ephemeral: true }); } catch (error) { logger.error("Captcha verification failed:", error.message); return interaction.reply({ content: "❌ Vérification impossible. Réessayez plus tard.", ephemeral: true }).catch(() => {}); } }
module.exports = { sendPanel, sendReminder, verify };
