const { ActionRowBuilder, ButtonBuilder, ButtonStyle, EmbedBuilder, PermissionsBitField } = require("discord.js");
const { supabase, mongoose } = require("../config/database");
const SuggestionVote = require("../models/SuggestionVote");
const { sendLog } = require("./logService");
const logger = require("../utils/logger");
const mongoReady = () => mongoose.connection.readyState === 1;
const buttons = (id) => [new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId(`suggestion_up:${id}`).setEmoji("👍").setLabel("Pour").setStyle(ButtonStyle.Success), new ButtonBuilder().setCustomId(`suggestion_down:${id}`).setEmoji("👎").setLabel("Contre").setStyle(ButtonStyle.Danger))];
const staffButtons = (id) => [new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId(`suggestion_approve:${id}`).setLabel("Accepter").setStyle(ButtonStyle.Success), new ButtonBuilder().setCustomId(`suggestion_reject:${id}`).setLabel("Refuser").setStyle(ButtonStyle.Danger), new ButtonBuilder().setCustomId(`suggestion_archive:${id}`).setLabel("Archiver").setStyle(ButtonStyle.Secondary), new ButtonBuilder().setCustomId(`suggestion_delete:${id}`).setLabel("Supprimer").setStyle(ButtonStyle.Secondary))];
function embed(suggestion) { return new EmbedBuilder().setColor(suggestion.status === "approved" ? "#57f287" : suggestion.status === "rejected" ? "#ed4245" : "#5865f2").setTitle("💡 Suggestion").setDescription(suggestion.content).addFields({ name: "État", value: suggestion.status, inline: true }, { name: "Votes", value: `👍 ${suggestion.upvotes || 0} · 👎 ${suggestion.downvotes || 0}`, inline: true }).setFooter({ text: `Suggestion #${suggestion.id} · par ${suggestion.user_id}` }).setTimestamp(new Date(suggestion.created_at)); }
async function createSuggestion(guild, config, user, content) { if (!supabase || !config.suggestions_enabled) throw new Error("Suggestions disabled or Supabase unavailable"); const channel = guild.channels.cache.get(config.suggestions_channel_id); if (!channel?.isTextBased?.() || !guild.members.me || !channel.permissionsFor(guild.members.me)?.has(PermissionsBitField.Flags.SendMessages)) throw new Error("Suggestion channel unavailable"); const { data, error } = await supabase.from("suggestions").insert({ guild_id: guild.id, user_id: user.id, content, status: "pending", upvotes: 0, downvotes: 0 }).select().single(); if (error) throw error; await channel.send({ embeds: [embed(data)], components: [...buttons(data.id), ...staffButtons(data.id)] }); await sendLog(guild, config, "log_moderation_channel_id", { title: "💡 Suggestion créée", color: "info", target: `${user} (${user.id})`, fields: [{ name: "Suggestion", value: content.slice(0, 1000) }] }); return data; }
async function vote(interaction, id, voteValue) { if (!mongoReady()) return interaction.reply({ content: "❌ Les votes sont temporairement indisponibles.", ephemeral: true }); const { data: suggestion } = await supabase.from("suggestions").select("*").eq("id", id).eq("guild_id", interaction.guild.id).maybeSingle(); if (!suggestion || suggestion.status !== "pending") return interaction.reply({ content: "❌ Cette suggestion n’est plus ouverte aux votes.", ephemeral: true }); try { const previous = await SuggestionVote.findOne({ suggestionId: id, userId: interaction.user.id }); if (previous?.vote === voteValue) { await previous.deleteOne(); } else if (previous) { previous.vote = voteValue; await previous.save(); } else await SuggestionVote.create({ suggestionId: id, userId: interaction.user.id, vote: voteValue }); const totals = await SuggestionVote.aggregate([{ $match: { suggestionId: id } }, { $group: { _id: "$vote", count: { $sum: 1 } } }]); const upvotes = totals.find((row) => row._id === 1)?.count || 0; const downvotes = totals.find((row) => row._id === -1)?.count || 0; const { data: updated, error } = await supabase.from("suggestions").update({ upvotes, downvotes }).eq("id", id).select().single(); if (error) throw error; await interaction.message.edit({ embeds: [embed(updated)], components: [...buttons(id), ...staffButtons(id)] }); const config = await require("./guildConfig").getGuildConfig(interaction.guild.id); await sendLog(interaction.guild, config, "log_moderation_channel_id", { title: "💡 Vote suggestion", color: "info", target: `${interaction.user} (${interaction.user.id})`, fields: [{ name: "ID", value: String(id), inline: true }, { name: "Vote", value: previous?.vote === voteValue ? "Retiré" : voteValue === 1 ? "Pour" : "Contre", inline: true }] }); await interaction.reply({ content: "✅ Vote mis à jour.", ephemeral: true }); } catch (error) { logger.error("Suggestion vote failed:", error.message); return interaction.reply({ content: "❌ Impossible de mettre à jour votre vote.", ephemeral: true }); } }
async function staffAction(interaction, id, action) { if (!interaction.member.permissions.has(PermissionsBitField.Flags.ManageGuild)) return interaction.reply({ content: "❌ Action réservée au staff.", ephemeral: true }); const { data: suggestion } = await supabase.from("suggestions").select("*").eq("id", id).eq("guild_id", interaction.guild.id).maybeSingle(); if (!suggestion) return interaction.reply({ content: "❌ Suggestion introuvable.", ephemeral: true }); if (action === "delete") { await supabase.from("suggestions").delete().eq("id", id); await interaction.message.delete().catch(() => {}); } else { const update = action === "approve" ? { status: "approved" } : action === "reject" ? { status: "rejected" } : { status: "archived", archived_at: new Date().toISOString() }; const { data: updated } = await supabase.from("suggestions").update(update).eq("id", id).select().single(); await interaction.message.edit({ embeds: [embed(updated)], components: [] }); } const config = await require("./guildConfig").getGuildConfig(interaction.guild.id); await sendLog(interaction.guild, config, "log_moderation_channel_id", { title: `💡 Suggestion ${action}`, color: action === "reject" || action === "delete" ? "danger" : "success", moderator: interaction.user, fields: [{ name: "ID", value: String(id) }] }); return interaction.reply({ content: "✅ Action enregistrée.", ephemeral: true }); }
module.exports = { createSuggestion, vote, staffAction, embed, buttons, staffButtons };
