import { Link } from 'react-router-dom';
import { Activity, ArrowRight, BellRing, CheckCircle2, MessageSquare, Settings2, ShieldCheck, Ticket, Users } from 'lucide-react';
import { StatCard } from '@/components/ui/StatCard';
import { useAuth } from '@/context/AuthContext';
import { useGuild } from '@/context/GuildContext';

const modules = [{ name: 'Bienvenue', path: 'welcome', enabled: 'welcome_enabled' }, { name: 'Tickets', path: 'tickets', enabled: 'tickets_enabled' }, { name: 'Logs', path: 'logs', enabled: 'logs_enabled' }, { name: 'AutoMod', path: 'automod', enabled: 'automod_enabled' }, { name: 'XP & niveaux', path: 'xplevels', enabled: 'xp_enabled' }, { name: 'Sécurité', path: 'security', enabled: 'security_enabled' }] as const;
const activity = [{ label: 'Configuration du serveur synchronisée', time: 'À l’instant', color: 'bg-neon-green' }, { label: 'Consultez les paramètres de modération', time: 'Prêt à configurer', color: 'bg-neon-yellow' }, { label: 'Personnalisez l’expérience des membres', time: 'Bienvenue & XP', color: 'bg-info' }];

export default function Home() {
  const { guilds } = useAuth(); const { selectedGuildId, config } = useGuild(); const guild = guilds.find((item) => item.id === selectedGuildId);
  const enabled = modules.filter((module) => config[module.enabled]).length;
  return <div className="space-y-6"><section className="relative overflow-hidden rounded-3xl border border-neon-green/20 bg-gradient-to-br from-neon-green/12 via-dark-800 to-dark-800 p-7 sm:p-9"><div className="absolute -right-16 -top-16 h-56 w-56 rounded-full bg-neon-green/15 blur-3xl" /><div className="relative flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div><div className="inline-flex items-center gap-2 text-xs font-bold uppercase tracking-widest text-neon-green"><CheckCircle2 className="h-4 w-4" />Espace serveur</div><h1 className="mt-3 text-3xl font-black sm:text-4xl">Bonjour, {guild?.name ?? 'communauté'}.</h1><p className="mt-2 max-w-xl text-sm leading-6 text-dark-300">Retrouvez les réglages essentiels, l’état de vos modules et les prochaines étapes pour votre serveur.</p></div><Link to="/dashboard/settings" className="btn-primary inline-flex shrink-0 items-center justify-center gap-2"><Settings2 className="h-4 w-4" />Configurer le serveur</Link></div></section>
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><StatCard icon={Users} label="Membres" value={guild?.member_count || '—'} trend={{ value: 0, isPositive: true }} /><StatCard icon={Activity} label="Modules actifs" value={`${enabled}/${modules.length}`} /><StatCard icon={MessageSquare} label="Messages" value="—" /><StatCard icon={Ticket} label="Tickets ouverts" value="—" /></div>
    <div className="grid gap-6 xl:grid-cols-5"><section className="module-card !cursor-default xl:col-span-3"><div className="flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-widest text-neon-green">Vue d’ensemble</p><h2 className="mt-1 text-xl font-bold">Modules de votre serveur</h2></div><span className="rounded-full border border-white/10 px-3 py-1 text-xs text-dark-300">{enabled} actifs</span></div><div className="mt-6 grid gap-2 sm:grid-cols-2">{modules.map((module) => <Link to={`/dashboard/${module.path}`} key={module.path} className="group flex items-center justify-between rounded-xl border border-white/8 bg-dark-700/50 p-3 transition hover:border-neon-green/25 hover:bg-dark-700"><span className="font-semibold text-sm">{module.name}</span><span className="flex items-center gap-2 text-xs"><i className={`h-2 w-2 rounded-full ${config[module.enabled] ? 'bg-neon-green shadow-[0_0_8px_#39ff14]' : 'bg-dark-400'}`} />{config[module.enabled] ? 'Actif' : 'Inactif'}<ArrowRight className="h-3.5 w-3.5 opacity-0 transition group-hover:opacity-100" /></span></Link>)}</div></section>
      <section className="module-card !cursor-default xl:col-span-2"><div className="flex items-center gap-2"><BellRing className="h-4 w-4 text-neon-yellow" /><h2 className="font-bold">Centre d’activité</h2></div><div className="mt-5 space-y-4">{activity.map((event) => <div key={event.label} className="flex gap-3"><i className={`mt-1.5 h-2 w-2 shrink-0 rounded-full ${event.color}`} /><div><p className="text-sm font-medium">{event.label}</p><p className="mt-0.5 text-xs text-dark-300">{event.time}</p></div></div>)}</div><div className="mt-6 border-t border-white/8 pt-4"><Link to="/dashboard/logs" className="text-sm font-bold text-neon-green hover:underline">Ouvrir les journaux <ArrowRight className="ml-1 inline h-3.5 w-3.5" /></Link></div></section></div>
    <section className="module-card !cursor-default flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-neon-green/10 text-neon-green"><ShieldCheck className="h-5 w-5" /></span><div><h2 className="font-bold">Votre serveur est prêt à être personnalisé</h2><p className="text-sm text-dark-300">Activez vos modules un à un et sauvegardez vos réglages.</p></div></div><Link to="/dashboard/welcome" className="btn-secondary inline-flex justify-center gap-2 !px-4">Commencer <ArrowRight className="h-4 w-4" /></Link></section>
  </div>;
}
