import { useState } from 'react';
import { AlertTriangle, LockKeyhole, Shield, ShieldCheck } from 'lucide-react';
import { ModuleHeader } from '@/components/ui/ModuleHeader';
import { Toggle } from '@/components/ui/Toggle';
import { FormField } from '@/components/ui/FormField';
import { SaveBar } from '@/components/ui/SaveBar';
import { Select } from '@/components/ui/Select';
import { useGuild } from '@/context/GuildContext';
import { useDiscordOptions } from '@/hooks/use-discord-options';
const protections = [{ id: 'raid', name: 'Anti Raid', text: 'Détecte les arrivées et comportements massifs.' }, { id: 'nuke', name: 'Anti Nuker', text: 'Surveille les actions destructrices sur le serveur.' }, { id: 'webhook', name: 'Anti Webhook', text: 'Prêt à surveiller les webhooks suspects.' }, { id: 'bot', name: 'Anti Bot', text: 'Prêt à contrôler les ajouts de bots.' }, { id: 'roles', name: 'Anti Role Delete', text: 'Prêt à détecter les suppressions de rôles.' }, { id: 'channels', name: 'Anti Channel Delete', text: 'Prêt à détecter les suppressions de salons.' }, { id: 'ban', name: 'Anti Mass Ban', text: 'Prêt à prévenir les bannissements massifs.' }, { id: 'kick', name: 'Anti Mass Kick', text: 'Prêt à prévenir les expulsions massives.' }];
export default function Security() {
  const { config, updateConfig } = useGuild(); const { roles } = useDiscordOptions(); const [dirty, setDirty] = useState(false); const [saving, setSaving] = useState(false); const [error, setError] = useState<string | null>(null); const [enabled, setEnabled] = useState(config.security_enabled); const [raid, setRaid] = useState(config.security_anti_raid); const [nuke, setNuke] = useState(config.security_anti_nuke); const [antiBot, setAntiBot] = useState(config.security_anti_bot); const [role, setRole] = useState(config.security_quarantine_role ?? '');
  const active = [raid, nuke, antiBot].filter(Boolean).length; const score = enabled ? 40 + active * 30 : 0; const change = (fn: () => void) => { fn(); setDirty(true); }; const save = async () => { try { setSaving(true); setError(null); await updateConfig({ security_enabled: enabled, security_anti_raid: raid, security_anti_nuke: nuke, security_anti_bot: antiBot, security_quarantine_role: role || null }); setDirty(false); } catch { setError('Impossible d’enregistrer le centre de sécurité.'); } finally { setSaving(false); } }; const reset = () => { setEnabled(config.security_enabled); setRaid(config.security_anti_raid); setNuke(config.security_anti_nuke); setAntiBot(config.security_anti_bot); setRole(config.security_quarantine_role ?? ''); setDirty(false); };
  const state = (id: string) => id === 'raid' ? raid : id === 'nuke' ? nuke : id === 'bot' ? antiBot : false;
  return <div className="space-y-6"><ModuleHeader icon={Shield} title="Security Center" description="Visualisez vos défenses et préparez les protections du serveur." toggleEnabled={enabled} onToggle={(value) => change(() => setEnabled(value))} />
    <div className="grid gap-4 md:grid-cols-3"><div className="module-card !cursor-default"><div className="flex items-center gap-4"><div className="grid h-16 w-16 place-items-center rounded-full border-4 border-neon-green/30 text-xl font-black text-neon-green">{score}</div><div><p className="font-bold">Score de sécurité</p><p className="text-sm text-dark-300">{score >= 80 ? 'Protection élevée' : score ? 'Protection à renforcer' : 'Protection désactivée'}</p></div></div></div><Stat label="Protections actives" value={`${active}/8`} /><Stat label="Dernières alertes" value="—" /></div>
    <div className="grid gap-6 xl:grid-cols-5"><section className="space-y-6 xl:col-span-3"><div className="module-card !cursor-default"><p className="text-xs font-bold uppercase tracking-widest text-neon-green">Bouclier du serveur</p><h2 className="mt-1 text-xl font-bold">Protections</h2><div className="mt-5 grid gap-2 sm:grid-cols-2">{protections.map((item) => <div key={item.id} className="flex gap-3 rounded-xl border border-white/8 bg-dark-700/45 p-4"><Toggle checked={state(item.id)} onChange={(value) => { if (item.id === 'raid') change(() => setRaid(value)); if (item.id === 'nuke') change(() => setNuke(value)); if (item.id === 'bot') change(() => setAntiBot(value)); }} /><div className="min-w-0 flex-1"><div className="flex items-center justify-between gap-2"><b className="text-sm">{item.name}</b><span className={state(item.id) ? 'text-xs font-bold text-neon-green' : 'text-xs text-dark-300'}>{state(item.id) ? 'Actif' : 'Prêt à connecter'}</span></div><p className="mt-1 text-xs leading-5 text-dark-300">{item.text}</p></div></div>)}</div></div><div className="module-card !cursor-default"><h2 className="font-bold">Réponse aux incidents</h2><div className="mt-4"><FormField label="Rôle de quarantaine"><Select options={roles} value={role} onChange={(value) => change(() => setRole(value))} placeholder="Choisir un rôle" /></FormField></div><p className="mt-4 text-xs leading-5 text-dark-300">Le rôle de quarantaine est appliqué par le bot lors des incidents Security détectés, lorsque ses permissions Discord le permettent.</p></div></section><aside className="xl:col-span-2"><div className="sticky top-24 module-card !cursor-default"><div className="flex items-center gap-2"><AlertTriangle className="h-4 w-4 text-neon-yellow" /><h2 className="font-bold">Alertes & recommandations</h2></div><div className="mt-5 space-y-3"><Notice icon={ShieldCheck} title="Centre de sécurité prêt" text="Activez Anti Raid et Anti Nuker pour améliorer le score." /><Notice icon={LockKeyhole} title="Quarantaine" text={role ? 'Rôle de quarantaine sélectionné.' : 'Sélectionnez un rôle de quarantaine.'} /></div><div className="mt-5 rounded-xl bg-[#313338] p-4"><p className="text-xs text-[#b5bac1]"># security-alerts</p><div className="mt-3 rounded border-l-4 border-neon-yellow bg-[#2b2d31] p-3 text-xs text-[#dbdee1]">Les alertes de sécurité apparaîtront ici, avec leur niveau, l’auteur et l’action appliquée.</div></div></div></aside></div><SaveBar isDirty={dirty} isSaving={saving} onSave={save} onReset={reset} error={error} /></div>;
}
function Stat({ label, value }: { label: string; value: string }) { return <div className="module-card !cursor-default"><strong className="text-2xl text-neon-green">{value}</strong><p className="mt-1 text-sm text-dark-300">{label}</p></div>; } function Notice({ icon: Icon, title, text }: { icon: typeof ShieldCheck; title: string; text: string }) { return <div className="flex gap-3 rounded-xl border border-white/8 bg-dark-700/45 p-3"><Icon className="mt-0.5 h-4 w-4 shrink-0 text-neon-green" /><div><p className="text-sm font-semibold">{title}</p><p className="mt-1 text-xs leading-5 text-dark-300">{text}</p></div></div>; }
