import { useState } from 'react';
import { Image, LogIn, Mail, Palette, Send, UserPlus } from 'lucide-react';
import { ModuleHeader } from '@/components/ui/ModuleHeader';
import { Toggle } from '@/components/ui/Toggle';
import { FormField } from '@/components/ui/FormField';
import { SaveBar } from '@/components/ui/SaveBar';
import { Select } from '@/components/ui/Select';
import { useGuild } from '@/context/GuildContext';

const channels = [{ value: 'ch-1', label: '#général' }, { value: 'ch-2', label: '#bienvenue' }, { value: 'ch-3', label: '#logs' }, { value: 'ch-4', label: '#départs' }];
const variables = ['{user}', '{username}', '{server}', '{memberCount}'];
export default function Welcome() {
  const { config, updateConfig } = useGuild(); const [isDirty, setIsDirty] = useState(false); const [isSaving, setIsSaving] = useState(false); const [error, setError] = useState<string | null>(null);
  const [welcomeEnabled, setWelcomeEnabled] = useState(config.welcome_enabled); const [goodbyeEnabled, setGoodbyeEnabled] = useState(config.goodbye_enabled); const [welcomeChannel, setWelcomeChannel] = useState(config.welcome_channel_id ?? ''); const [goodbyeChannel, setGoodbyeChannel] = useState(config.goodbye_channel_id ?? ''); const [welcomeMessage, setWelcomeMessage] = useState(config.welcome_message ?? ''); const [goodbyeMessage, setGoodbyeMessage] = useState(config.goodbye_message ?? ''); const [embed, setEmbed] = useState(config.welcome_embed_enabled); const [color, setColor] = useState(config.welcome_embed_color); const [dm, setDm] = useState(config.welcome_dm_enabled); const [dmMessage, setDmMessage] = useState(config.welcome_dm_message ?? '');
  const change = (fn: () => void) => { fn(); setIsDirty(true); }; const save = async () => { try { setIsSaving(true); setError(null); await updateConfig({ welcome_enabled: welcomeEnabled, welcome_channel_id: welcomeChannel || null, welcome_message: welcomeMessage || null, welcome_embed_enabled: embed, welcome_embed_color: color, welcome_dm_enabled: dm, welcome_dm_message: dmMessage || null, goodbye_enabled: goodbyeEnabled, goodbye_channel_id: goodbyeChannel || null, goodbye_message: goodbyeMessage || null }); setIsDirty(false); } catch { setError('Impossible d’enregistrer les messages.'); } finally { setIsSaving(false); } };
  const reset = () => { setWelcomeEnabled(config.welcome_enabled); setGoodbyeEnabled(config.goodbye_enabled); setWelcomeChannel(config.welcome_channel_id ?? ''); setGoodbyeChannel(config.goodbye_channel_id ?? ''); setWelcomeMessage(config.welcome_message ?? ''); setGoodbyeMessage(config.goodbye_message ?? ''); setEmbed(config.welcome_embed_enabled); setColor(config.welcome_embed_color); setDm(config.welcome_dm_enabled); setDmMessage(config.welcome_dm_message ?? ''); setIsDirty(false); };
  const insert = (value: string) => change(() => setWelcomeMessage((current) => `${current}${current ? ' ' : ''}${value}`));
  return <div className="space-y-6"><ModuleHeader icon={LogIn} title="Bienvenue & départ" description="Créez une première impression mémorable pour chaque membre." toggleEnabled={welcomeEnabled || goodbyeEnabled} onToggle={(value) => change(() => { setWelcomeEnabled(value); setGoodbyeEnabled(value); })} />
    <div className="grid gap-6 xl:grid-cols-5"><section className="space-y-6 xl:col-span-3"><div className="module-card !cursor-default"><div className="flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-widest text-neon-green">Éditeur</p><h2 className="mt-1 text-xl font-bold">Message de bienvenue</h2></div><Toggle checked={welcomeEnabled} onChange={(value) => change(() => setWelcomeEnabled(value))} /></div><div className="mt-6 grid gap-5 sm:grid-cols-2"><FormField label="Salon de bienvenue"><Select options={channels} value={welcomeChannel} onChange={(value) => change(() => setWelcomeChannel(value))} placeholder="Choisir un salon" /></FormField><FormField label="Couleur de l’embed"><div className="flex items-center gap-3"><input aria-label="Couleur de l’embed" type="color" value={color} onChange={(event) => change(() => setColor(event.target.value))} className="h-10 w-12 rounded-lg border border-white/10 bg-transparent" /><code className="text-sm text-dark-300">{color}</code></div></FormField></div><FormField label="Contenu du message" className="mt-5"><textarea value={welcomeMessage} onChange={(event) => change(() => setWelcomeMessage(event.target.value))} className="input-field min-h-28 resize-y" placeholder="Bienvenue {user} sur {server} !" /></FormField><div className="mt-3 flex flex-wrap gap-2">{variables.map((variable) => <button key={variable} onClick={() => insert(variable)} className="rounded-lg border border-white/10 bg-dark-700 px-2.5 py-1.5 text-xs font-semibold text-neon-green hover:border-neon-green/30">{variable}</button>)}</div><div className="mt-6 grid gap-3 border-t border-white/8 pt-5 sm:grid-cols-2"><Row icon={Palette} label="Envoyer comme embed" text="Présentation enrichie dans Discord." checked={embed} onChange={(value) => change(() => setEmbed(value))} /><Row icon={Mail} label="Message privé" text="Envoyé automatiquement lors de l’arrivée." checked={dm} onChange={(value) => change(() => setDm(value))} /></div>{dm && <FormField label="Message privé" className="mt-4"><textarea value={dmMessage} onChange={(event) => change(() => setDmMessage(event.target.value))} className="input-field min-h-24 resize-y" placeholder="Bienvenue {user} sur {server} !" /></FormField>}</div>
      <div className="module-card !cursor-default"><div className="flex items-center justify-between"><div><h2 className="text-xl font-bold">Message de départ</h2><p className="mt-1 text-sm text-dark-300">Un dernier message configurable pour votre communauté.</p></div><Toggle checked={goodbyeEnabled} onChange={(value) => change(() => setGoodbyeEnabled(value))} /></div><div className="mt-5 grid gap-5 sm:grid-cols-2"><FormField label="Salon de départ"><Select options={channels} value={goodbyeChannel} onChange={(value) => change(() => setGoodbyeChannel(value))} placeholder="Choisir un salon" /></FormField><FormField label="Message"><input value={goodbyeMessage} onChange={(event) => change(() => setGoodbyeMessage(event.target.value))} className="input-field" placeholder="Au revoir {user} !" /></FormField></div></div></section>
      <aside className="xl:col-span-2"><div className="sticky top-24 module-card !cursor-default"><div className="flex items-center gap-2"><Image className="h-4 w-4 text-neon-yellow" /><h2 className="font-bold">Aperçu en direct</h2></div><p className="mt-1 text-xs text-dark-300">Aucun message n’est envoyé pendant la prévisualisation.</p><div className="mt-5 rounded-xl bg-[#313338] p-4"><p className="mb-3 text-xs font-semibold text-[#b5bac1]"># bienvenue</p><div className="flex gap-3"><div className="grid h-9 w-9 shrink-0 place-items-center rounded-full bg-neon-green font-bold text-dark-900">C</div><div className="min-w-0"><p className="text-sm font-semibold text-white">CIVRAT <span className="rounded bg-[#5865f2] px-1 text-[9px]">BOT</span></p><div className="mt-1 overflow-hidden rounded border-l-4 bg-[#2b2d31]" style={{ borderColor: color }}><div className="p-3"><p className="font-semibold text-white">Bienvenue !</p><p className="mt-1 whitespace-pre-wrap text-sm text-[#dbdee1]">{(welcomeMessage || 'Bienvenue {user} sur {server} !').replace('{user}', '@Nouveau membre').replace('{server}', 'CIVRAT')}</p></div></div></div></div></div><button className="btn-secondary mt-5 inline-flex w-full items-center justify-center gap-2"><Send className="h-4 w-4" />Tester le message</button><p className="mt-2 text-center text-xs text-dark-300">Le test sera disponible via le bot Discord.</p></div></aside></div>
    <SaveBar isDirty={isDirty} isSaving={isSaving} onSave={save} onReset={reset} error={error} /></div>;
}
function Row({ icon: Icon, label, text, checked, onChange }: { icon: typeof UserPlus; label: string; text: string; checked: boolean; onChange: (value: boolean) => void }) { return <div className="flex gap-3 rounded-xl bg-dark-700/50 p-3"><Icon className="mt-0.5 h-4 w-4 text-neon-green" /><div className="flex-1"><p className="text-sm font-semibold">{label}</p><p className="mt-1 text-xs text-dark-300">{text}</p></div><Toggle checked={checked} onChange={onChange} /></div>; }
